### ISSUE TITLE
An example would be of great use.

### ISSUE THREAD

**Issue by vishnup95** [sergei-zelinsky/react-critical-css#2]
So I am trying to reduce the CSS in my site and I came across this. Critical was just not cutting it for me. Seems promising from React side. Can you whip up an example to show the working, the docs are a tough read. Much appreciated.

**Comment by serhiizelinsky** [comment]
Hey @vishnup95,

First of all the way, I used this library is server-side rendering. In case when we have a large app with a lot of CSS it is critical to send only CSS a web page needs for the initial render.

For example, we have the next routing setup:

```jsx
<Switch>
	<Route path="/" exact component={HomePage}/>
	<Route path="/about" exact component={AboutPage}/>
</Switch>
```

and the next components:

```jsx
// HomePage component
import React, {Component} from 'react';
import {withStyles} from 'react-critical-css';
import homePageStyles from './index.css';

class HomePage extends Component {
  // ...
  
  render(){
    return (
      <div className="home-page">Home Page</div>
    );
  }
}

export default withStyles(homePageStyles)(App);
```

```jsx
// AboutPage component
import React, {Component} from 'react';
import {withStyles} from 'react-critical-css';
import aboutPageStyles from './index.css';

class AboutPage extends Component {
  // ...
  
  render(){
    return (
      <div className="about-page">Home Page</div>
    );
  }
}

export default withStyles(aboutPageStyles)(App);
```

When a user requests a `/` `URL` a server should send him only styles for a `HomePage` component.

On the stage of server-side rendering when the `/` route will be rendered only styles for `HomePage` will be stored in the `styleRegistry` like shown below (example with Express.js):

```jsx
// ...
import {renderToString} from 'react-dom/server';
import {CriticalCSSProvider, StyleRegistry} from 'react-critical-css';

// ...

app.use((req, res, next) => {
	const styleRegistry = new StyleRegistry(); // create new style registry

	const appString = renderToString(
    	<CriticalCSSProvider registry={styleRegistry}>
      		<App/>
    	</CriticalCSSProvider>
	);

	const criticalCSS = styleRegistry.getCriticalCSS(); // insert this styles into result HTML

	res.send(
		// response HTML here
	)
})
```

Feel free to ask me if you have additional questions 🙂 

Thanks

**Comment by vishnup95** [comment]
Thanks for the reply. How do I use this when I have connect wrapped around the component.  For e.g: export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Home);

How will this work? How can i add withStyles?

**Comment by serhiizelinsky** [comment]
You can simply write the next way:

```js
export default withStyles(styles)(
	connect(
		mapStateToProps,
		mapDispatchToProps
	)(Home)
);
```

or the same using `compose` function:

```js
export default compose(
	withStyles(styles),
	connect(mapStateToProps, mapDispatchToProps)
)(Home);
```

**Comment by serhiizelinsky** [comment]
Hey @vishnup95,

does that work for you?

**Comment by vishnup95** [comment]
Oops, I forgot to update here. Sorry. I didn't get any errors from the library, but the thing I wanted never happened. My sandbox environment has a whole crashed. I am using SSR with renderServerApp.js along with loadable. I think something is messing up the render.

**Comment by aravindsiruvuru-sureify** [comment]
```
	const styleRegistry = new StyleRegistry(); // create new style registry

	const appString = renderToString(
    	<CriticalCSSProvider registry={styleRegistry}>
      		<App/>
    	</CriticalCSSProvider>
	);

	const criticalCSS = styleRegistry.getCriticalCSS();

```

where should i use this piece of code ??  


if my index.js is in this way 
`ReactDOM.render(<App/>, document.getElementById('root'));`

please replay ASAP @sergei-zelinsky

**Comment by serhiizelinsky** [comment]
Hello @AravindSiruvuru-Sureify,

The code you provided should be used on a `NodeJS` server.
It extracts all the `CSS` which was used while rendering the `App` component on the server.
After that, you can include it in the page HTML, for example:

```js
const html = `
  <html>
    <head>
      // ...
      <style>
        ${criticalCSS}
      </style>
    </head>
    <body>
      <div id="root">
        ${appString}
      </div>
    </body>
  </html>
`;
```


Thanks

**Comment by aravindsiruvuru-sureify** [comment]
@sergei-zelinsky  thank you so much for a quick reply 

am currently working on a frontend react application. 

so my files will be as follows 
**index.js**
```
import ReactDOM from "react-dom";
import App from "./App";

const rootElement = document.getElementById("root");
ReactDOM.render(
  <StrictMode>
    <App />
  </StrictMode>,
  rootElement
);
```

**App.js**
```
import About from "./About";
import Home from "./Home";
import { BrowserRouter as Router, Switch, Route, Link } from "react-router-dom";
export default function App() {
  return (
    <Router>
      <Switch>
        <Route path="/about">
          <About />
        </Route>
        <Route path="/">
          <Home />
        </Route>
      </Switch>
    </Router>
  );
}
```

**About.js**

```
import React, { Component } from "react";
import { withStyles } from "react-critical-css";
import aboutStyles from "./styles.css";

class About extends Component {
  render() {
    return <div>About Page</div>;
  }
}

export default withStyles(aboutStyles)(About);
```

**Home.js**
```
import React, { Component } from "react";
import { withStyles } from "react-critical-css";
import homeStyles from "./styles.css";

class Home extends Component {
  render() {
    return <div>Home Page</div>;
  }
}

export default withStyles(homeStyles)(Home);
```

The same code is available in the code sandbox [https://codesandbox.io/s/loving-leftpad-ek8td](https://codesandbox.io/s/loving-leftpad-ek8td)
you can complete the code there if possible .. which will be more helpful for all frontend devs over there who want to get started with our react-critical-CSS


```
	const styleRegistry = new StyleRegistry(); // create new style registry

	const appString = renderToString(
    	<CriticalCSSProvider registry={styleRegistry}>
      		<App/>
    	</CriticalCSSProvider>
	);

	const criticalCSS = styleRegistry.getCriticalCSS();
```

so, can you let me know where will the above criticalCSS variable will be used  in basic react application

**Comment by vishnup95** [comment]
@AravindSiruvuru-Sureify He meant node-server as in an SSR react app. What you posted is a client-side application.

**Comment by aravindsiruvuru-sureify** [comment]
@vishnup95 @sergei-zelinsky will this won't work with the client-side application. 
Thank you.

**Comment by serhiizelinsky** [comment]
Hey @AravindSiruvuru-Sureify,

I think you simply don't need this library. As @vishnup95 mentioned it's only applicable for Server-Side Rendering: where you want to ship only the CSS for the current page.

As far as I understood you want `code-splitting`. For example, to do not load the code of the `About ` page while it hasn't been visited.
If yes, there is a great article in React documentation called [Code-Splitting](https://reactjs.org/docs/code-splitting.html#reactlazy). Basically, you need to use dynamic imports with your screen components and that should do the trick 🙂 

Here is the example from documentation:

```jsx
import React, { Suspense, lazy } from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';

const Home = lazy(() => import('./routes/Home'));
const About = lazy(() => import('./routes/About'));

const App = () => (
  <Router>
    <Suspense fallback={<div>Loading...</div>}>
      <Switch>
        <Route exact path="/" component={Home}/>
        <Route path="/about" component={About}/>
      </Switch>
    </Suspense>
  </Router>
);

```

Hope that helps 🙂
