### ISSUE TITLE
Using with SCSS

### ISSUE THREAD

**Issue by nickmurr** [sergei-zelinsky/react-critical-css#3]
Hey Sergei, is there any way to use react-critical-css with .scss?

**Comment by serhiizelinsky** [comment]
Hey @NickMurr,

I think there is no problem to use `react-critical-css` with no matter which style processor you use. If you use SASS there are several loaders you have in your bundler config. So when you require those files they are processed by sass-loader and css-loader. After that, you have a simple string of CSS and you can pass it to `withStyles HOC`.

In the "Getting Started"  there is example of webpack config with required loaders, except style-loader which is not needed for SSR.
https://github.com/webpack-contrib/sass-loader#getting-started

Hope that helps. Let me know if you have any questions.

Thanks
